project:
  type: book
  output-dir: docs

book:
  title: "학생맞춤통합지원 체계 운영실태 조사 분석보고서"
  author: "학생맞춤지원담당관 지역협력복지팀(a.k.a. Donny)"
  chapters:
    - index.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    number-sections: false
    code-fold: true
    css: styles.css
