project:
  type: book
  output-dir: docs

book:
  title: "학생맞춤통합지원 체계 운영실태 조사 분석보고서"
  author: "학생맞춤지원담당관 지역협력복지팀(a.k.a. Donny)"
  chapters:
    - index.qmd
    - Report_Int(20250928)_final.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: show

execute:
  freeze: auto
