project:
  type: website
  output-dir: docs

website:
  title: "학생맞춤통합지원 체계 운영실태 조사"
  navbar:
    left:
      - href: Report_Int.qmd
        text: "분석보고서"

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    toc-title: "목차"
    number-sections: true
    code-fold: true
    code-summary: "코드 보기"
