name: Quarto Publish

on:
  push:
    branches: [ main ]

# ← github-actions[bot]이 gh-pages 브랜치에 쓸 수 있게 권한을 줍니다
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # (옵션) 일부 패키지가 시스템 라이브러리를 요구할 때 도움 됩니다
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

      - name: Install R packages
        run: |
          Rscript -e 'pkgs <- c("rmarkdown","knitr","dplyr","ggplot2","readxl","janitor","stringr","tidyr","tidytext","cluster","factoextra","gridExtra","RColorBrewer","scales","kableExtra","DT","gt","showtext","forcats","tibble"); inst <- rownames(installed.packages()); to_install <- setdiff(pkgs, inst); if(length(to_install)) install.packages(to_install, repos="https://cloud.r-project.org")'

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
